package com.androidatlas.notes.core.database.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "sync_operations")
data class SyncOperationEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0, // auto-incrementing primary key for the queue table
    val localId: String, // UUID generated by client, echoed back by server
    val operationType: String, // "UPSERT" or "DELETE"
    val noteId: String?, // null for brand-new notes
    val title: String?,
    val content: String?,
    val folderOrLabel: String?,
    val clientUpdatedAt: String, // ISO 8601 timestamp — when this change was made locally
    val status: String = "PENDING" // PENDING, SYNCING, FAILED, SYNCED
)
